### ISSUE TITLE
SDX integration progress tracking

### ISSUE THREAD

**Issue by congwang09** [atlanticwave-sdx/sdx-continuous-development#94]
This issue tracks the SDX end to end integration. The items that have been done, and the items that needs to be addressed.

- [x] Kytos sets up the underlying network infra
- [x] Kytos sends new topology and topology updates to sdx-lc
- [x] sdx-lc sends topology to sdx-controller via RabbitMQ
- [x] sdx-controller calls pce to construct the global topology
- [ ] Users use Meican to send connection request to sdx-controller
- [x] #95
- [x] sdx-controller sends breakdown connection to LCs via RabbitMQ
- [x] LC sends connection request to Kytos
- [ ] Kytos sets up the connection on the underlying network infra

**Comment by JulioIbarra** [comment]
Sorry. Closed this issue by accident.
